export interface Part {
  id: number
  article: string
  partNumber: string
  name: string
  price: string
  category: string
  description?: string
  weight?: string
  material?: string
  manufacturer?: string
  warranty?: string
  inStock?: boolean
  compatibleWith?: string[]
}

export const kpu9Parts: Part[] = [
  {
    id: 1,
    article: "KPU9-KPU-9-15-000",
    partNumber: "КПУ 9.15.000",
    name: "Стяжка",
    price: "1194,1",
    category: "cultivators",
    description:
      "Стяжка для культиватора КПУ-9. Обеспечивает надежное крепление рабочих органов. Изготовлена из высокопрочной стали с антикоррозийным покрытием.",
    weight: "2.5 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9", "КПУ-9М"],
  },
  {
    id: 2,
    article: "KPU9-KPU-9-11-000",
    partNumber: "КПУ 9.11.000",
    name: "Комплект электрооборудования",
    price: "5791,8",
    category: "cultivators",
    description:
      "Полный комплект электрооборудования для культиватора КПУ-9. Включает проводку, разъемы, световые элементы и защитные компоненты.",
    weight: "4.2 кг",
    material: "Медь, пластик",
    manufacturer: "АгроТех",
    warranty: "24 месяца",
    inStock: true,
    compatibleWith: ["КПУ-9", "КПУ-9М", "КПУ-12"],
  },
  {
    id: 3,
    article: "KPU9-KPU-9-00-076",
    partNumber: "КПУ 9.00.076",
    name: "Щиток сигнальный",
    price: "579,36",
    category: "cultivators",
    description:
      "Сигнальный щиток для обозначения габаритов культиватора. Светоотражающий, соответствует требованиям безопасности дорожного движения.",
    weight: "0.8 кг",
    material: "Пластик, светоотражающая пленка",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9", "КПУ-12"],
  },
  {
    id: 4,
    article: "KPU9-KPU-9-00-070",
    partNumber: "КПУ 9.00.070",
    name: "Комплект оборудования щитков передних",
    price: "5123,17",
    category: "cultivators",
    description:
      "Комплект передних защитных щитков для культиватора. Защищает рабочие органы от повреждений и предотвращает разброс почвы.",
    weight: "8.5 кг",
    material: "Сталь 3",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 5,
    article: "KPU9-KPU-9-00-060",
    partNumber: "КПУ 9.00.060",
    name: "Комплект оборудования щитков задних",
    price: "4884,89",
    category: "cultivators",
    description:
      "Комплект задних защитных щитков для культиватора. Обеспечивает равномерное распределение обработанной почвы.",
    weight: "7.8 кг",
    material: "Сталь 3",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 6,
    article: "KPU9-KPU-9-13-000",
    partNumber: "КПУ 9.13.000",
    name: "Комплект оборудования с двухточечной навеской",
    price: "4414,71",
    category: "cultivators",
    description:
      "Комплект для двухточечной навески культиватора на трактор. Обеспечивает быстрое и надежное соединение.",
    weight: "15.2 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "24 месяца",
    inStock: true,
    compatibleWith: ["КПУ-9", "Тракторы МТЗ", "Тракторы ЮМЗ"],
  },
  {
    id: 7,
    article: "KPU9-KPU-9-17-000",
    partNumber: "КПУ 9.17.000",
    name: "Комплект оборудования с прицепной пётлей",
    price: "4087,06",
    category: "cultivators",
    description:
      "Комплект прицепного устройства для культиватора. Позволяет использовать культиватор в прицепном варианте агрегатирования.",
    weight: "12.4 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "24 месяца",
    inStock: false,
    compatibleWith: ["КПУ-9", "КПУ-12"],
  },
  {
    id: 8,
    article: "KPU9-KPU-9-08-030",
    partNumber: "КПУ 9.08.030",
    name: "Секция боронки и КПУ 9.08.030 в сборе с крепежом",
    price: "2803,63",
    category: "harrows",
    description:
      "Секция боронки в сборе с крепежными элементами. Предназначена для выравнивания и рыхления поверхности почвы после обработки.",
    weight: "6.3 кг",
    material: "Сталь 65Г",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 9,
    article: "KPU9-KPU-9-08-010",
    partNumber: "КПУ 9.08.010",
    name: "Секции боронок КПУ 9.08.010 и КПУ 9.08.010-01",
    price: "2850,09",
    category: "harrows",
    description:
      "Комплект секций боронок для культиватора. Обеспечивает качественное боронование и выравнивание почвы.",
    weight: "5.8 кг",
    material: "Сталь 65Г",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 10,
    article: "KPU9-KPU-9-08-030-K",
    partNumber: "КПУ 9.08.030",
    name: "Кронштейн КПУ 9.08.030",
    price: "693,66",
    category: "harrows",
    description: "Кронштейн крепления секции боронки. Изготовлен из прочной стали, обеспечивает надежную фиксацию.",
    weight: "1.2 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9", "КПУ-12"],
  },
  {
    id: 11,
    article: "KPU9-KPU-9-08-020",
    partNumber: "КПУ 9.08.020",
    name: "Секция боронки",
    price: "2839,69",
    category: "harrows",
    description: "Отдельная секция боронки для замены изношенных элементов. Высокая износостойкость зубьев.",
    weight: "5.5 кг",
    material: "Сталь 65Г",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 12,
    article: "KPU9-KPU-9-08-000",
    partNumber: "КПУ 9.08.000",
    name: "Комплект боронок КПУ 9.08.000 (для КПУ-9)",
    price: "4181,52",
    category: "harrows",
    description: "Полный комплект боронок для культиватора КПУ-9. Включает все необходимые секции и крепеж.",
    weight: "18.5 кг",
    material: "Сталь 65Г",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 13,
    article: "KPU9-KPU-9-06-030-01",
    partNumber: "КПУ 9.06.030-01",
    name: "Тяга в сборе с креплением",
    price: "2269,42",
    category: "cultivators",
    description: "Тяга в сборе с комплектом крепежных элементов. Обеспечивает передачу усилия на рабочие органы.",
    weight: "3.8 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 14,
    article: "KPU9-KPU-9-06-030",
    partNumber: "КПУ 9.06.030",
    name: "Тяга в сборе с креплением",
    price: "1681,23",
    category: "cultivators",
    description: "Тяга с креплением для культиватора. Стандартная комплектация.",
    weight: "3.2 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 15,
    article: "KPU9-KPU-9-06-000A",
    partNumber: "КПУ 9.06.000А",
    name: "Комплект катков КПУ 9.06.000А (Для КПУ-9)",
    price: "5392,37",
    category: "soil-compactors",
    description: "Комплект прикатывающих катков для культиватора КПУ-9. Обеспечивает уплотнение почвы после обработки.",
    weight: "45.0 кг",
    material: "Сталь, резина",
    manufacturer: "АгроТех",
    warranty: "24 месяца",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 16,
    article: "KPU9-KPU-9-06-100A",
    partNumber: "КПУ 9.06.100А",
    name: "Каток КПУ 9.06.100А",
    price: "2684,08",
    category: "soil-compactors",
    description: "Прикатывающий каток для культиватора. Диаметр 530 мм, обеспечивает равномерное уплотнение.",
    weight: "22.5 кг",
    material: "Сталь, резина",
    manufacturer: "АгроТех",
    warranty: "24 месяца",
    inStock: true,
    compatibleWith: ["КПУ-9", "КПУ-12"],
  },
  {
    id: 17,
    article: "KPU9-KPU-9-12-010-03",
    partNumber: "КПУ 9.12.010-03",
    name: "Подвеска",
    price: "1662,4",
    category: "cultivators",
    description: "Подвеска рабочих органов культиватора. Вариант исполнения 03.",
    weight: "4.5 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 18,
    article: "KPU9-KPU-9-12-010-02",
    partNumber: "КПУ 9.12.010-02",
    name: "Подвеска",
    price: "1265,85",
    category: "cultivators",
    description: "Подвеска рабочих органов культиватора. Вариант исполнения 02.",
    weight: "4.0 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 19,
    article: "KPU9-KPU-9-12-010-01",
    partNumber: "КПУ 9.12.010-01",
    name: "Подвеска",
    price: "1758,62",
    category: "cultivators",
    description: "Подвеска рабочих органов культиватора. Вариант исполнения 01.",
    weight: "4.8 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: false,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 20,
    article: "KPU9-KPU-9-12-010",
    partNumber: "КПУ 9.12.010",
    name: "Подвеска",
    price: "1699,02",
    category: "cultivators",
    description: "Базовая подвеска рабочих органов культиватора КПУ-9.",
    weight: "4.2 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 21,
    article: "KPU9-KPU-9-12-000",
    partNumber: "КПУ 9.12.000",
    name: "Комплект подвесок КПУ 9.12.000 (Для КПУ-9)",
    price: "4357,43",
    category: "cultivators",
    description: "Полный комплект подвесок для культиватора КПУ-9. Включает все варианты исполнения.",
    weight: "24.0 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 22,
    article: "KPU9-KPU-9-05-010",
    partNumber: "КПУ 9.05.010",
    name: "Секция выравнивателя КПУ 9.05.010",
    price: "2978,59",
    category: "deep-rippers",
    description: "Секция выравнивателя для глубокой обработки почвы. Рабочая глубина до 12 см.",
    weight: "8.5 кг",
    material: "Сталь 65Г",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 23,
    article: "KPU9-KPU-9-05-010-01",
    partNumber: "КПУ 9.05.010-01",
    name: "Секция выравнивателей КПУ 9.05.010-01",
    price: "3203,39",
    category: "deep-rippers",
    description: "Секция выравнивателей модификации 01. Улучшенная конструкция.",
    weight: "9.2 кг",
    material: "Сталь 65Г",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 24,
    article: "KPU9-KPU-9-05-070",
    partNumber: "КПУ 9.05.070",
    name: "Выравниватель",
    price: "1171,3",
    category: "deep-rippers",
    description: "Отдельный выравниватель для замены изношенного. Высокая износостойкость.",
    weight: "2.8 кг",
    material: "Сталь 65Г",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9", "КПУ-12"],
  },
  {
    id: 25,
    article: "KPU9-KPU-9-05-000",
    partNumber: "КПУ 9.05.000",
    name: "Комплект выравнивателей КПУ 9.05.000 (Для КПУ-9)",
    price: "5325,88",
    category: "deep-rippers",
    description: "Полный комплект выравнивателей для культиватора КПУ-9. 36 штук в комплекте.",
    weight: "32.0 кг",
    material: "Сталь 65Г",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 26,
    article: "KPU9-KPU-9-00-010",
    partNumber: "КПУ 9.00.010",
    name: "Колесо опорное в сборе с винтом",
    price: "1662,4",
    category: "cultivators",
    description: "Опорное колесо с регулировочным винтом. Позволяет настраивать глубину обработки.",
    weight: "12.5 кг",
    material: "Сталь, резина",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 27,
    article: "KPU9-KPU-9-02-000",
    partNumber: "КПУ 9.02.000",
    name: "Подкат транспортных колёс в сборе с осями",
    price: "1791,82",
    category: "cultivators",
    description: "Подкат для перевода культиватора в транспортное положение. Шины 500/55-20.",
    weight: "85.0 кг",
    material: "Сталь, резина",
    manufacturer: "АгроТех",
    warranty: "24 месяца",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 28,
    article: "KPU9-KPU-9-03-010",
    partNumber: "КПУ 9.03.010",
    name: "Сница",
    price: "1282,95",
    category: "plows",
    description: "Сница (дышло) для соединения культиватора с трактором. Прочная конструкция.",
    weight: "18.0 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "24 месяца",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 29,
    article: "KPU9-KPU-9-01-030",
    partNumber: "КПУ 9.01.030",
    name: "Крыло в сборе с крепежом",
    price: "4049,41",
    category: "cultivators",
    description: "Крыло рамы культиватора в сборе с полным комплектом крепежа.",
    weight: "45.0 кг",
    material: "Сталь 3",
    manufacturer: "АгроТех",
    warranty: "24 месяца",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 30,
    article: "KPU9-KPU-9-01-010",
    partNumber: "КПУ 9.01.010",
    name: "Рама в сборе с КПУ 9.01.020 Приставка и крепежом",
    price: "12301,03",
    category: "cultivators",
    description:
      "Основная рама культиватора КПУ-9 в сборе с приставкой и полным комплектом крепежа. Центральный элемент конструкции.",
    weight: "350.0 кг",
    material: "Сталь 09Г2С",
    manufacturer: "АгроТех",
    warranty: "36 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 31,
    article: "KPU9-KPU-9-00-408",
    partNumber: "КПУ 9.00.408",
    name: "Кронштейн в сборе с креплением (для КПУ 9.06.030-01)",
    price: "822,49",
    category: "cultivators",
    description: "Кронштейн для крепления тяги КПУ 9.06.030-01.",
    weight: "1.8 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 32,
    article: "KPU9-KPU-9-01-010-W",
    partNumber: "КПУ 9.01.010",
    name: "КПУ 9.01.010 в сборе с крыльями",
    price: "1124,11",
    category: "cultivators",
    description: "Рама с установленными крыльями. Готовый узел для сборки.",
    weight: "125.0 кг",
    material: "Сталь 09Г2С",
    manufacturer: "АгроТех",
    warranty: "24 месяца",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 33,
    article: "KPU9-KPU-9-00-090",
    partNumber: "КПУ 9.00.090",
    name: "Держатель для шлангов",
    price: "1157,72",
    category: "seeders",
    description: "Держатель для гидравлических шлангов. Обеспечивает аккуратную прокладку магистралей.",
    weight: "0.5 кг",
    material: "Сталь, пластик",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9", "КПУ-12"],
  },
  {
    id: 34,
    article: "KPU9-KPU-9-00-085",
    partNumber: "КПУ 9.00.085",
    name: "Оси в сборе",
    price: "1793,21",
    category: "cultivators",
    description: "Комплект осей для опорных колес культиватора.",
    weight: "8.5 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 35,
    article: "KPU9-KPU-9-00-080",
    partNumber: "КПУ 9.00.080",
    name: "Оси в сборе",
    price: "693,55",
    category: "cultivators",
    description: "Оси в сборе для культиватора. Стандартная комплектация.",
    weight: "6.2 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9"],
  },
  {
    id: 36,
    article: "KPU9-KPU-9-00-040A",
    partNumber: "КПУ 9.00.040А",
    name: "Винт в сборе",
    price: "586,75",
    category: "cultivators",
    description: "Регулировочный винт в сборе. Для настройки глубины обработки.",
    weight: "1.2 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-9", "КПУ-12"],
  },
]

export const kpu12Parts: Part[] = [
  {
    id: 101,
    article: "KPU12-KPU-9-06-100A",
    partNumber: "КПУ 9.06.100А",
    name: "Каток КПУ 9.06.100А (для КПУ 12)",
    price: "2213,88",
    category: "soil-compactors",
    description: "Прикатывающий каток для культиватора КПУ-12. Диаметр 530 мм.",
    weight: "22.5 кг",
    material: "Сталь, резина",
    manufacturer: "АгроТех",
    warranty: "24 месяца",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 102,
    article: "KPU12-KPU-9-06-100A-02",
    partNumber: "КПУ 9.06.100А-02",
    name: "Каток КПУ 9.06.100А-02 (для КПУ 12)",
    price: "2751,49",
    category: "soil-compactors",
    description: "Прикатывающий каток модификации 02 для культиватора КПУ-12.",
    weight: "24.0 кг",
    material: "Сталь, резина",
    manufacturer: "АгроТех",
    warranty: "24 месяца",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 103,
    article: "KPU12-KPU-9-08-000-01",
    partNumber: "КПУ 9.08.000-01",
    name: "Комплект боронок КПУ 9.08.000-01 (для КПУ-12)",
    price: "5409,5",
    category: "harrows",
    description: "Полный комплект боронок для культиватора КПУ-12. Включает все секции и крепеж.",
    weight: "24.5 кг",
    material: "Сталь 65Г",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 104,
    article: "KPU12-KPU-9-05-000-01",
    partNumber: "КПУ 9.05.000-01",
    name: "Комплект выравнивателей КПУ 9.05.000-01 (Для КПУ-12)",
    price: "5878,21",
    category: "deep-rippers",
    description: "Полный комплект выравнивателей для культиватора КПУ-12. 48 штук в комплекте.",
    weight: "42.0 кг",
    material: "Сталь 65Г",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 105,
    article: "KPU12-KPU-9-06-000A",
    partNumber: "КПУ 9.06.000А",
    name: "Комплект катков КПУ 9.06.000А (Для КПУ-12)",
    price: "4137,85",
    category: "soil-compactors",
    description: "Комплект прикатывающих катков для культиватора КПУ-12.",
    weight: "58.0 кг",
    material: "Сталь, резина",
    manufacturer: "АгроТех",
    warranty: "24 месяца",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 106,
    article: "KPU12-KPU-9-12-000-01",
    partNumber: "КПУ 9.12.000-01",
    name: "Комплект подвесок КПУ 9.12.000-01 (Для КПУ-12)",
    price: "5164,62",
    category: "cultivators",
    description: "Полный комплект подвесок для культиватора КПУ-12.",
    weight: "32.0 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 107,
    article: "KPU12-KPU-9-00-010",
    partNumber: "КПУ 9.00.010",
    name: "Колесо опорное в сборе с винтом (для КПУ 12)",
    price: "1600,86",
    category: "cultivators",
    description: "Опорное колесо с регулировочным винтом для КПУ-12.",
    weight: "12.5 кг",
    material: "Сталь, резина",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 108,
    article: "KPU12-KPU-9-00-040A",
    partNumber: "КПУ 9.00.040А",
    name: "Винт в сборе (для КПУ 12)",
    price: "617,39",
    category: "cultivators",
    description: "Регулировочный винт в сборе для КПУ-12.",
    weight: "1.2 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 109,
    article: "KPU12-KPU-9-00-060",
    partNumber: "КПУ 9.00.060",
    name: "Комплект оборудования щитков задних (Для КПУ 12)",
    price: "4988,18",
    category: "cultivators",
    description: "Комплект задних защитных щитков для культиватора КПУ-12.",
    weight: "9.5 кг",
    material: "Сталь 3",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 110,
    article: "KPU12-KPU-9-00-070",
    partNumber: "КПУ 9.00.070",
    name: "Комплект оборудования щитков передних (Для КПУ 12)",
    price: "5484,23",
    category: "cultivators",
    description: "Комплект передних защитных щитков для культиватора КПУ-12.",
    weight: "10.2 кг",
    material: "Сталь 3",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 111,
    article: "KPU12-KPU-9-00-076",
    partNumber: "КПУ 9.00.076",
    name: "Щиток сигнальный (Для КПУ 12)",
    price: "402,29",
    category: "cultivators",
    description: "Сигнальный щиток для обозначения габаритов КПУ-12.",
    weight: "0.8 кг",
    material: "Пластик, светоотражающая пленка",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 112,
    article: "KPU12-KPU-9-00-080",
    partNumber: "КПУ 9.00.080",
    name: "Оси в сборе (для КПУ 12)",
    price: "718,67",
    category: "cultivators",
    description: "Оси в сборе для культиватора КПУ-12.",
    weight: "6.5 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 113,
    article: "KPU12-KPU-9-00-085",
    partNumber: "КПУ 9.00.085",
    name: "Оси в сборе (для КПУ 12)",
    price: "2799,55",
    category: "cultivators",
    description: "Комплект осей для опорных колес КПУ-12.",
    weight: "9.0 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 114,
    article: "KPU12-KPU-9-00-090",
    partNumber: "КПУ 9.00.090",
    name: "Держатель для шлангов (для КПУ 12)",
    price: "1375,62",
    category: "seeders",
    description: "Держатель для гидравлических шлангов КПУ-12.",
    weight: "0.6 кг",
    material: "Сталь, пластик",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 115,
    article: "KPU12-KPU-9-00-408",
    partNumber: "КПУ 9.00.408",
    name: "Кронштейн в сборе с креплением (для КПУ 12.06.030-01)",
    price: "822,51",
    category: "cultivators",
    description: "Кронштейн для крепления тяги КПУ-12.",
    weight: "1.8 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 116,
    article: "KPU12-KPU-9-00-408-2",
    partNumber: "КПУ 9.00.408",
    name: "Кронштейн в сборе с креплением (для КПУ 12.06.030)",
    price: "774,73",
    category: "cultivators",
    description: "Кронштейн для крепления тяги КПУ-12. Вариант 2.",
    weight: "1.6 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 117,
    article: "KPU12-KPU-9-01-010",
    partNumber: "КПУ 9.01.010",
    name: "КПУ 9.01.010 в сборе с крыльями (для КПУ 12)",
    price: "565,86",
    category: "cultivators",
    description: "Рама с установленными крыльями для КПУ-12.",
    weight: "135.0 кг",
    material: "Сталь 09Г2С",
    manufacturer: "АгроТех",
    warranty: "24 месяца",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 118,
    article: "KPU12-KPU-9-01-010-Z",
    partNumber: "КПУ 9.01.010",
    name: "КПУ 9.01.010 в сборе с крыльями и закрылками (для КПУ 12)",
    price: "1955,78",
    category: "cultivators",
    description: "Рама с крыльями и закрылками для КПУ-12.",
    weight: "155.0 кг",
    material: "Сталь 09Г2С",
    manufacturer: "АгроТех",
    warranty: "24 месяца",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 119,
    article: "KPU12-KPU-9-01-010-R",
    partNumber: "КПУ 9.01.010",
    name: "Рама в сборе с КПУ 12.01.020 Приставка и крепежом (для КПУ 12)",
    price: "14490,64",
    category: "cultivators",
    description: "Основная рама культиватора КПУ-12 в сборе с приставкой и полным комплектом крепежа.",
    weight: "420.0 кг",
    material: "Сталь 09Г2С",
    manufacturer: "АгроТех",
    warranty: "36 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 120,
    article: "KPU12-KPU-9-01-030",
    partNumber: "КПУ 9.01.030",
    name: "Крыло в сборе с крепежом (для КПУ 12)",
    price: "3716,15",
    category: "cultivators",
    description: "Крыло рамы культиватора КПУ-12 в сборе с крепежом.",
    weight: "52.0 кг",
    material: "Сталь 3",
    manufacturer: "АгроТех",
    warranty: "24 месяца",
    inStock: false,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 121,
    article: "KPU12-KPU-9-01-060",
    partNumber: "КПУ 9.01.060",
    name: "Закрылок (для КПУ 12)",
    price: "1719,45",
    category: "cultivators",
    description: "Закрылок для культиватора КПУ-12.",
    weight: "8.5 кг",
    material: "Сталь 3",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 122,
    article: "KPU12-KPU-9-02-000",
    partNumber: "КПУ 9.02.000",
    name: "Подкат транспортных колёс в сборе с осями (для КПУ 12)",
    price: "2692,53",
    category: "cultivators",
    description: "Подкат для перевода КПУ-12 в транспортное положение.",
    weight: "95.0 кг",
    material: "Сталь, резина",
    manufacturer: "АгроТех",
    warranty: "24 месяца",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 123,
    article: "KPU12-KPU-9-03-010",
    partNumber: "КПУ 9.03.010",
    name: "Сница (для КПУ 12)",
    price: "1554,05",
    category: "plows",
    description: "Сница (дышло) для соединения КПУ-12 с трактором.",
    weight: "22.0 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "24 месяца",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 124,
    article: "KPU12-KPU-9-05-070",
    partNumber: "КПУ 9.05.070",
    name: "Выравниватель (для КПУ 12)",
    price: "1439,06",
    category: "deep-rippers",
    description: "Выравниватель для культиватора КПУ-12.",
    weight: "3.0 кг",
    material: "Сталь 65Г",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 125,
    article: "KPU12-KPU-9-06-030",
    partNumber: "КПУ 9.06.030",
    name: "Тяга в сборе с креплением (Для КПУ-12)",
    price: "2265,36",
    category: "cultivators",
    description: "Тяга в сборе с креплением для КПУ-12.",
    weight: "4.0 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 126,
    article: "KPU12-KPU-9-06-030-01",
    partNumber: "КПУ 9.06.030-01",
    name: "Тяга в сборе с креплением (Для КПУ-12)",
    price: "1624,03",
    category: "cultivators",
    description: "Тяга в сборе с креплением для КПУ-12. Модификация 01.",
    weight: "3.5 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 127,
    article: "KPU12-KPU-9-08-020",
    partNumber: "КПУ 9.08.020",
    name: "Секция боронки (Для КПУ 12)",
    price: "3270,24",
    category: "harrows",
    description: "Секция боронки для культиватора КПУ-12.",
    weight: "6.0 кг",
    material: "Сталь 65Г",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 128,
    article: "KPU12-KPU-9-11-000",
    partNumber: "КПУ 9.11.000",
    name: "Комплект электрооборудования (Для КПУ 12)",
    price: "4174,89",
    category: "cultivators",
    description: "Полный комплект электрооборудования для КПУ-12.",
    weight: "4.8 кг",
    material: "Медь, пластик",
    manufacturer: "АгроТех",
    warranty: "24 месяца",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 129,
    article: "KPU12-KPU-9-12-010",
    partNumber: "КПУ 9.12.010",
    name: "Подвеска (для КПУ 12)",
    price: "1439,24",
    category: "cultivators",
    description: "Базовая подвеска для культиватора КПУ-12.",
    weight: "4.5 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 130,
    article: "KPU12-KPU-9-12-010-01",
    partNumber: "КПУ 9.12.010-01",
    name: "Подвеска (для КПУ 12)",
    price: "1327,32",
    category: "cultivators",
    description: "Подвеска модификации 01 для КПУ-12.",
    weight: "4.2 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 131,
    article: "KPU12-KPU-9-12-010-02",
    partNumber: "КПУ 9.12.010-02",
    name: "Подвеска (для КПУ 12)",
    price: "1704,03",
    category: "cultivators",
    description: "Подвеска модификации 02 для КПУ-12.",
    weight: "4.8 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 132,
    article: "KPU12-KPU-9-12-010-03",
    partNumber: "КПУ 9.12.010-03",
    name: "Подвеска (для КПУ 12)",
    price: "1448,28",
    category: "cultivators",
    description: "Подвеска модификации 03 для КПУ-12.",
    weight: "4.6 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: false,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 133,
    article: "KPU12-KPU-9-13-000",
    partNumber: "КПУ 9.13.000",
    name: "Комплект оборудования с двухточечной навеской (Для КПУ 12)",
    price: "5034,64",
    category: "cultivators",
    description: "Комплект для двухточечной навески КПУ-12 на трактор.",
    weight: "18.0 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "24 месяца",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 134,
    article: "KPU12-KPU-9-15-000",
    partNumber: "КПУ 9.15.000",
    name: "Стяжка (Для КПУ 12)",
    price: "948,24",
    category: "cultivators",
    description: "Стяжка для культиватора КПУ-12.",
    weight: "2.8 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 135,
    article: "KPU12-KPU-9-17-000",
    partNumber: "КПУ 9.17.000",
    name: "Комплект оборудования с прицепной пётлей (Для КПУ 12)",
    price: "5935,31",
    category: "cultivators",
    description: "Комплект прицепного устройства для КПУ-12.",
    weight: "14.5 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "24 месяца",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 136,
    article: "KPU12-KPU-9-08-030",
    partNumber: "КПУ 9.08.030",
    name: "Кронштейн КПУ 9.08.030 (Для КПУ 12)",
    price: "809,51",
    category: "harrows",
    description: "Кронштейн крепления секции боронки для КПУ-12.",
    weight: "1.4 кг",
    material: "Сталь 45",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 137,
    article: "KPU12-KPU-9-08-010",
    partNumber: "КПУ 9.08.010",
    name: "Секции боронок КПУ 9.08.010 и КПУ 9.08.010-01 (Для КПУ 12)",
    price: "1987,83",
    category: "harrows",
    description: "Комплект секций боронок для КПУ-12.",
    weight: "6.2 кг",
    material: "Сталь 65Г",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 138,
    article: "KPU12-KPU-9-08-030-S",
    partNumber: "КПУ 9.08.030",
    name: "Секция боронки и КПУ 9.08.030 в сборе с крепежом (Для КПУ 12)",
    price: "3454,44",
    category: "harrows",
    description: "Секция боронки в сборе с крепежом для КПУ-12.",
    weight: "7.0 кг",
    material: "Сталь 65Г",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 139,
    article: "KPU12-KPU-9-05-010-01",
    partNumber: "КПУ 9.05.010-01",
    name: "Секция выравнивателей КПУ 9.05.010-01 (для КПУ 12)",
    price: "2601,23",
    category: "deep-rippers",
    description: "Секция выравнивателей модификации 01 для КПУ-12.",
    weight: "9.5 кг",
    material: "Сталь 65Г",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 140,
    article: "KPU12-KPU-9-05-010",
    partNumber: "КПУ 9.05.010",
    name: "Секция выравнивателя КПУ 9.05.010 (для КПУ 12)",
    price: "2569,06",
    category: "deep-rippers",
    description: "Секция выравнивателя для КПУ-12.",
    weight: "9.0 кг",
    material: "Сталь 65Г",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
  {
    id: 141,
    article: "KPU12-KPU-9-05-020",
    partNumber: "КПУ 9.05.020",
    name: "Секция выравнивателя КПУ 9.05.020 (для КПУ 12)",
    price: "2980,12",
    category: "deep-rippers",
    description: "Секция выравнивателя модели 020 для КПУ-12.",
    weight: "9.8 кг",
    material: "Сталь 65Г",
    manufacturer: "АгроТех",
    warranty: "12 месяцев",
    inStock: true,
    compatibleWith: ["КПУ-12"],
  },
]

export const allParts = [...kpu9Parts, ...kpu12Parts]

export function getProductById(id: number): Part | undefined {
  return allParts.find((p) => p.id === id)
}

export const categories = [
  { id: "all", name: "Все", icon: "Grid3X3" },
  { id: "cultivators", name: "Культиваторы", icon: "Tractor" },
  { id: "plows", name: "Плуги", icon: "Shovel" },
  { id: "harrows", name: "Бороны", icon: "Rows3" },
  { id: "seeders", name: "Сеялки", icon: "Sprout" },
  { id: "soil-compactors", name: "Почвоуплотнители", icon: "CircleDot" },
  { id: "deep-rippers", name: "Глубокорыхлители", icon: "ArrowDownToLine" },
]

export const bestSellers = [
  allParts.find((p) => p.id === 2)!,
  allParts.find((p) => p.id === 30)!,
  allParts.find((p) => p.id === 15)!,
  allParts.find((p) => p.id === 12)!,
  allParts.find((p) => p.id === 119)!,
  allParts.find((p) => p.id === 103)!,
  allParts.find((p) => p.id === 104)!,
  allParts.find((p) => p.id === 135)!,
].filter(Boolean)
